bteq << EOF
.LOGON {add logon bits};

REPLACE FUNCTION syslib.isValidNPI (npi VARCHAR(15) CHARACTER SET LATIN) 
 RETURNS INTEGER
 SPECIFIC isValidNPI 
 LANGUAGE C 
 NO SQL  
 PARAMETER STYLE SQL 
 DETERMINISTIC 
 CALLED ON NULL INPUT 
 EXTERNAL NAME isValidNPI
;

.QUIT;

EOF
